server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${sky.datasource.driver-class-name}
    url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${sky.datasource.username}
    password: ${sky.datasource.password}
    type: com.alibaba.druid.pool.DruidDataSource # 指定数据库连接池
  jackson:
    serialization:
      fail-on-unwrapped-type-identifiers:

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml # 默认：classpath*:/mapper/**/*.xml
  # （Configuration）的配置大都为 MyBatis 原生支持的配置，这意味着您可以通过 MyBatis XML 配置文件的形式进行配置。
  configuration:
    mapUnderscoreToCamelCase: true # 默认：true
  type-aliases-package:

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

springdoc:
  packages-to-scan: # 指定要扫描的包（及其子包）
    - com.sky.controller
  swagger-ui:
    enabled: true  # 开启/禁止swagger，默认为true
    path: /swagger3.html  # 修改Swagger UI 页面的请求路径。默认情况下，Swagger UI 页面将在以下 url 中提供：`http://server:port/context-path/swagger-ui.html`（server：server：服务器名称或 IP；port：服务器端口；context-path：应用程序的上下文路径）
    version:

  api-docs:
    enabled: true # 开启/禁止api-docs
    # OpenAPI 描述将在以下 url 中提供，格式为 json：http://server:port/context-path/swagger-ui.htmlhttp://server:port/context-path/v3/api-docs（server：server：服务器名称或 IP；port：服务器端口；context-path：应用程序的上下文路径）
    path: /api-docs # 默认是json格式，可以在路径后加上`.yaml`以获取yaml格式的文档
    groups:
      enabled: true # 开启分组

  use-management-port: false # 在执行器管理端口上公开 swagger-ui。默认值：false。

  pre-loading-enabled: false # 提前加载


  default-support-form-data: true

  paths-to-exclude: # 配置不包含在swagger文档中的api
    - /api/test/**
    - /api/mockito/data
---
sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: fallingdust
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token